import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Hunting Coder !</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <h1 className={styles.heading}>Hunting Coder !</h1>
          <p className={styles.para}>
            A blog for a hunting coders by a hunting coder.
          </p>
          <Image
            src="/img.png"
            width={800}
            height={500}
            className={styles.img}
          />
        </div>
        <div className={styles.blogs}>
          <h2 className={styles.blogItem}>Latest Blogs</h2>
          <div className={styles.blogItem}>
            <Link href={'/blogPost/learn-javasvript'}>
              <h3 className={styles.headLine}>
                How to learn Javascript in 2023
              </h3>
            </Link>
            <p className={styles.para}>
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Mollitia
              quidem impedit sed reprehenderit, praesentium illo obcaecati?
            </p>
          </div>
          <div className={styles.blogItem}>
            <h3 className={styles.headLine}>How to learn Javascript in 2023</h3>
            <p className={styles.para}>
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Mollitia
              quidem impedit sed reprehenderit, praesentium illo obcaecati?
            </p>
          </div>
          <div className={styles.blogItem}>
            <h3 className={styles.headLine}>How to learn Javascript in 2023</h3>
            <p className={styles.para}>
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Mollitia
              quidem impedit sed reprehenderit, praesentium illo obcaecati?
            </p>
          </div>
        </div>
      </main>
    </>
  );
}
