import Head from "next/head";
// import Image from 'next/image'
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={`${styles.nav} ${inter.className}`}>
        <ul>
          <li>About</li>
          <li>Blogs</li>
          <li>Services</li>
          <li>Contacts</li>
        </ul>
      </nav>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.center}>
          <h1 className={styles.heading}>Hunting Coder !</h1>
          <p className={styles.para}>
            A blog by a hunting coders by a hunting coder.
          </p>
        </div>
        <div className={styles.blogs}>
          <div className={styles.blogItem}>
            <h1 className={styles.headLine}>How to learn Javascript in 2023</h1>
            <p className={styles.para}>
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Mollitia
              quidem impedit sed reprehenderit, praesentium illo obcaecati?
            </p>
          </div>
          <div className={styles.blogItem}>
            <h1 className={styles.headLine}>How to learn Javascript in 2023</h1>
            <p className={styles.para}>
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Mollitia
              quidem impedit sed reprehenderit, praesentium illo obcaecati?
            </p>
          </div>
          <div className={styles.blogItem}>
            <h1 className={styles.headLine}>How to learn Javascript in 2023</h1>
            <p className={styles.para}>
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Mollitia
              quidem impedit sed reprehenderit, praesentium illo obcaecati?
            </p>
          </div>
        </div>
      </main>
    </>
  );
}
